### DISCUSSION TITLE
Add more annotation functions, such as underlining, notes, etc.

### DISCUSSION THREAD

**Discussion by PennHui666** [RyotaUshio/obsidian-pdf-plus#80] [Q&A]
The experience of annotating PDF directly in Obsidian is very good, but highlighting alone is not enough to meet all the requirements for annotation experience. I don’t know if anyone has the same needs as me, but I think this feature request may be out of the original design intention of PDF++, so if developers think this is not necessary, that’s okay.

**Comment by RyotaUshio** [comment]
In fact, underlining can be already achieved by the following custom CSS snippets.

```css
.pdf-plus-backlink-highlight-layer .pdf-plus-backlink.pdf-plus-backlink-selection {
    background-color: transparent;
    border-bottom: 0.1em solid var(--pdf-plus-color);
    padding-bottom: 0;
    opacity: 1.0;
    border-radius: 0;
}
```

Result:

<img width="988" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/8ee8c1a0-e37f-467d-9469-32a858123de3">

---

As for "notes", do you mean something like sticky notes?

<img width="387" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/2adfe04c-e200-4819-8696-35f28931c9f6">

If so, the main aim of PDF++ is annotating PDFs with regular markdown notes, so my suggestion is to use backlink highlighting+hover editor.

https://github.com/RyotaUshio/obsidian-pdf-plus/issues/75#issuecomment-1974851305

In my opinion, this method is superior to the conventional method of embedding sticky notes directly into PDF files because it allows us to connect the notes to anything in our vaults. But if you don't agree with it, I'm also interested in your opinion.
