### ISSUE TITLE
[FR] Different Colors For Bounding Rectangle for backlinked annotations

### ISSUE THREAD

**Issue by Paining1** [RyotaUshio/obsidian-pdf-plus#332]
### Describe your request

Hi, I really like the bounding rectangle, it lets me know which sections I highlighted but haven't used. But I was wondering if you could allow it to be different colors? Just so it looks well with the color I used..

Thanks for the great plugin!

**Comment by RyotaUshio** [comment]
Most PDF++ components can be styled with CSS snippets. For example, if you want to make the rectangle boxes black, use this:

```css
.pdf-plus-backlink-highlight-layer .pdf-plus-backlink.pdf-plus-backlink-fit-r {
    border-color: black;
}
```

Note: If you want to learn what CSS selector to target by yourself, the following forum thread is a good resource for learning how to do so.

https://forum.obsidian.md/t/obsidian-css-inspector-workflow/58178
