### ISSUE TITLE
[FR] An option for setting sidebar width

### ISSUE THREAD

**Issue by SSmJaE** [RyotaUshio/obsidian-pdf-plus#52]
it's very disturbing to resize the sidebar whenever open a new PDF file, i found a way to automatically adjust the width of the sidebar

```css
.pdf-content-container.node-insert-event.sidebarOpen {
    --sidebar-width: 330px;
}
```

we could provide a setting option to set the width, this may help others who suffering the same pain

**Comment by RyotaUshio** [comment]
Hi, thanks for the idea! This would be a wonderful addition to the Style Settings menu.
Can I ask why `.node-insert-event.sidebarOpen` is needed? In my environment, just 

```css
.pdf-content-container {
    --sidebar-width: 330px;
}
```

seems to work well.
